# Generated by Django 4.1.3 on 2023-02-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('from_emp', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('approved', 'apporoved'), ('unapproved', 'unapproved')], max_length=30)),
                ('emp_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.emp')),
            ],
        ),
    ]
